import { useState } from "react";
import type { SettingsSnapshot } from "../types.ts";

export interface ModelsSettingsProps { readonly settings: SettingsSnapshot; readonly onDefaultModel: (id: string) => void; readonly onLogin: (providerId: string, apiKey: string, modelId?: string) => Promise<void>; readonly onLogout: (providerId: string) => Promise<void>; readonly onCustomProvider: (input: { readonly api: "openai-responses" | "openai-chat-completions" | "anthropic-messages"; readonly baseUrl: string; readonly apiKey: string; readonly modelId: string }) => Promise<void>; }

export function ModelsSettings({ settings, onDefaultModel, onLogin, onLogout, onCustomProvider }: ModelsSettingsProps): React.JSX.Element {
	const [selected, setSelected] = useState(settings.defaults.providerId ?? settings.runtime.providerId);
	const [apiKey, setApiKey] = useState("");
	const [custom, setCustom] = useState({ api: "openai-responses" as "openai-responses" | "openai-chat-completions" | "anthropic-messages", baseUrl: "", modelId: "" });
	const provider = settings.providers.find((item) => item.id === selected) ?? settings.providers[0];
	return <div className="settings-section" aria-labelledby="models-title"><h3 id="models-title">Models</h3><p className="settings-section-note">Credentials never leave the server. Environment-managed credentials are displayed but cannot be edited here.</p><div className="provider-list">{settings.providers.map((item) => <article className={`provider-card${item.id === selected ? " is-selected" : ""}`} key={item.id}><button type="button" className="provider-card-main" onClick={() => setSelected(item.id)}><strong>{item.name}</strong><span>{item.id} · {item.models.length} models</span></button><span className={`provider-status status-${item.apiKeySource}`}>{item.apiKeySource === "environment" ? "Environment" : item.configured ? "Configured" : "Not configured"}</span></article>)}</div>{provider ? <div className="model-controls"><label>Default model<select value={settings.defaults.providerId === provider.id ? settings.defaults.modelId ?? "" : ""} onChange={(event) => onDefaultModel(event.target.value)}><option value="">Select a model</option>{provider.models.map((model) => <option value={model.id} key={model.id}>{model.name} ({model.id})</option>)}</select></label>{provider.apiKeySource === "environment" ? <p className="readonly-note">API key is managed by the environment.</p> : <div className="login-row"><input aria-label={`${provider.name} API key`} type="password" value={apiKey} onChange={(event) => setApiKey(event.target.value)} placeholder={provider.configured ? "Replace API key" : "API key"} /><button type="button" onClick={() => void onLogin(provider.id, apiKey, provider.models[0]?.id).then(() => setApiKey(""))} disabled={!apiKey.trim()}>Save key</button>{provider.configured ? <button type="button" className="button-quiet" onClick={() => void onLogout(provider.id)}>Log out</button> : null}</div>}</div> : null}<div className="custom-provider-form"><strong>Custom Provider</strong><div className="login-row"><select aria-label="Custom Provider API" value={custom.api} onChange={(event) => setCustom({ ...custom, api: event.target.value as typeof custom.api })}><option value="openai-responses">OpenAI Responses</option><option value="openai-chat-completions">Chat Completions</option><option value="anthropic-messages">Anthropic Messages</option></select><input aria-label="Custom Provider Base URL" placeholder="https://gateway.example/v1" value={custom.baseUrl} onChange={(event) => setCustom({ ...custom, baseUrl: event.target.value })} /><input aria-label="Custom Provider model" placeholder="Model ID" value={custom.modelId} onChange={(event) => setCustom({ ...custom, modelId: event.target.value })} /><input aria-label="Custom Provider API key" type="password" placeholder="API key" value={apiKey} onChange={(event) => setApiKey(event.target.value)} /><button type="button" disabled={!custom.baseUrl || !custom.modelId || !apiKey} onClick={() => void onCustomProvider({ ...custom, apiKey }).then(() => setApiKey(""))}>Add custom</button></div></div></div>;
}
