import { Moon, Monitor, Sun, X } from "lucide-react";
import { IconButton } from "./IconButton.tsx";

interface SettingsOverlayProps { readonly open: boolean; readonly onClose: () => void; readonly provider?: string; readonly model?: string; readonly theme: "light" | "dark" | "system"; readonly onThemeChange: (theme: "light" | "dark" | "system") => void; }

export function SettingsOverlay({ open, onClose, provider, model, theme, onThemeChange }: SettingsOverlayProps): React.JSX.Element | null {
	if (!open) return null;
	return <div className="overlay" role="presentation"><section className="settings-panel" role="dialog" aria-modal="true" aria-labelledby="settings-title"><div className="settings-header"><div><p className="eyebrow">Workspace preferences</p><h2 id="settings-title">Settings</h2></div><IconButton label="Close settings" icon={X} onClick={onClose} /></div><nav className="settings-nav" aria-label="Settings sections"><button className="settings-nav-item is-selected" type="button">General</button><button className="settings-nav-item" type="button">Models</button><button className="settings-nav-item" type="button">Shortcuts</button></nav><div className="settings-content"><div className="setting-row"><div><strong>Appearance</strong><span>Choose how di-code looks on this device.</span></div><div className="theme-options">{([['light', Sun, 'Light'], ['dark', Moon, 'Dark'], ['system', Monitor, 'System']] as const).map(([value, ThemeIcon, label]) => <button className={`theme-option${theme === value ? " is-selected" : ""}`} key={value} onClick={() => onThemeChange(value)} type="button"><ThemeIcon size={15} />{label}</button>)}</div></div><div className="setting-row"><div><strong>Active provider</strong><span>Read from your existing di-code settings.</span></div><code>{provider ?? "Unavailable"}</code></div><div className="setting-row"><div><strong>Model</strong><span>Runtime model selected for this workspace.</span></div><code>{model ?? "Unavailable"}</code></div></div></section></div>;
}
