// This file is auto-generated by src/models.ts.
// Do not edit manually. Run node --experimental-strip-types packages/ai/src/models.ts.

import type { Model } from "./types.ts";

export const MODELS: readonly Model[] = [
	{
		id: "gpt-4o",
		name: "GPT-4o",
		provider: "openai",
		api: "openai-responses",
		baseUrl: "https://api.openai.com/v1",
		input: ["text", "image"],
		reasoning: false,
		contextWindow: 128000,
		maxOutputTokens: 16384,
		cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
	},
	{
		id: "gpt-5.6-terra",
		name: "gpt-5.6-terra",
		provider: "openai",
		api: "openai-responses",
		baseUrl: "https://api.openai.com/v1",
		input: ["text"],
		reasoning: true,
		contextWindow: 200000,
		maxOutputTokens: 100000,
		cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
	},
	{
		id: "o3-mini",
		name: "o3-mini",
		provider: "openai",
		api: "openai-responses",
		baseUrl: "https://api.openai.com/v1",
		input: ["text"],
		reasoning: true,
		contextWindow: 200000,
		maxOutputTokens: 100000,
		cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
	},
];
