import { createContext, useContext, useEffect, useMemo, useState } from "react";

export type WebLocale = "en" | "zh-CN";

const zh: Readonly<Record<string, string>> = {
	"Project resources detected": "检测到项目资源", "Load project plugins and integrations?": "是否加载项目插件和集成？", "Plugins, Skills, and MCP configuration come from this workspace. Review them before allowing project-local code and instructions to load.": "插件、Skill 和 MCP 配置来自当前工作区。允许项目本地代码和指令加载前，请先确认这些内容。", "Not now": "暂不加载", "Trust and load": "信任并加载", "Loading...": "加载中...", "Unable to inspect project resources.": "无法检查项目资源。", "Unable to update project trust.": "无法更新工作区信任状态。",
	"Connected": "已连接", "Unavailable": "不可用", "Connecting": "连接中", "Connecting...": "连接中...", "Removing...": "移除中...",
	"Workspace navigation": "工作区导航", "Open sidebar": "打开侧栏", "Collapse sidebar": "收起侧栏", "Workspace actions": "工作区操作", "New session in workspace": "在工作区中新建会话", "Rename": "重命名", "Delete this workspace?": "删除此工作区？", "Drop a folder here": "将文件夹拖到这里", "or choose a folder": "或选择文件夹", "Drag a folder from your file manager.": "请从文件管理器拖入文件夹。",
	"Select workspace": "选择工作区", "New session": "新建会话", "Sessions": "会话", "Workspaces": "工作区", "Search sessions": "搜索会话", "Close search": "关闭搜索", "Workspace display options": "工作区显示选项", "Add workspace": "添加工作区", "Choose a folder": "选择文件夹", "Choose a local folder to add it to this WebUI.": "选择一个本地文件夹，将其添加到此 WebUI。", "Cancel": "取消", "Adding...": "添加中...", "Unable to add workspace.": "无法添加工作区。", "Settings": "设置",
	"Open navigation": "打开导航", "Session": "会话", "Standard mode": "标准模式", "Session log": "会话日志",
	"Turn ideas into code.": "让想法落地成代码", "What are we building today?": "今天我们要构建什么？", "Ask di-code to explore your workspace, write code, or solve a problem.": "让 di-code 探索工作区、编写代码或解决问题。", "Workspace": "工作区", "Standard session": "标准会话", "Current workspace and mode": "当前工作区和模式",
	"Conversation views": "对话视图", "Chat": "对话", "Trajectory": "轨迹", "Reconnecting to session events...": "正在重新连接会话事件...", "Compacting context": "正在压缩上下文",
	"Workspace preferences": "工作区偏好", "Close settings": "关闭设置", "Settings sections": "设置分区", "General": "常规", "Models": "模型", "Skills": "技能", "Plugins": "插件", "Presets": "预设", "Trust": "信任", "Shortcuts": "快捷键", "Loading settings...": "正在加载设置...",
	"Preferences are shared with the terminal client. The active Session keeps its runtime until it is idle.": "偏好设置与终端客户端共享。当前会话会持续使用现有运行时，直到进入空闲状态。", "Appearance": "外观", "Choose the appearance for this browser.": "选择此浏览器的外观。", "Language": "语言", "Terminal and WebUI locale": "终端和 WebUI 语言", "中文": "中文", "English": "English", "Permission mode": "权限模式", "Default for future turns": "后续回合的默认设置", "Ask before tools": "使用工具前询问", "Allow tools": "允许使用工具", "Deny tools": "拒绝使用工具", "Thinking": "思考强度", "Current Session runtime level": "当前会话运行时级别", "Default": "默认", "Low": "低", "Medium": "中", "High": "高", "Max": "最高", "Configuration source": "配置来源", "Environment + settings": "环境变量 + 设置", "Environment-managed values are read-only.": "环境变量管理的值为只读。",
	"Credentials never leave the server. Environment-managed credentials cannot be edited here.": "凭据不会离开服务器。此处无法编辑由环境变量管理的凭据。", "Provider": "Provider", "Custom": "自定义", "Configured": "已配置", "Not configured": "未配置", "Environment": "环境变量", "models": "个模型", "saved models": "个已保存模型", "Configure a gateway": "配置网关", "Model": "模型", "Select a model": "选择模型", "API key": "API 密钥", "Save key": "保存密钥", "Log out": "退出登录", "Custom Provider": "自定义 Provider", "Update connection": "更新连接", "New connection": "新建连接", "Use model": "使用模型", "Model ID": "模型 ID", "Base URL": "基础 URL", "Choose or enter a model ID": "选择或输入模型 ID", "Save custom provider": "保存自定义 Provider", "Add custom provider": "添加自定义 Provider",
	"Start a session to work with di-code.": "开始会话以使用 di-code。", "You": "你", "Tool": "工具", "Used skill": "使用技能", "Completed": "已完成", "Retry": "重试", "Allow this tool to run?": "允许此工具运行吗？", "Accept": "接受", "Deny": "拒绝", "Preparing response...": "正在准备回复...", "Thinking and tool activity": "思考与工具活动", "Conversation transcript": "对话记录", "Copy": "复制", "Branch into a new conversation": "分支为新对话", "Waiting for response": "正在等待回复", "Action required": "需要操作", "Plan review": "计划审阅", "Approval required": "需要审批", "Approve": "批准", "Cancel interaction": "取消交互",
	"Light": "浅色", "Dark": "深色", "System": "跟随系统", "Message di-code": "发送消息给 di-code", "Steer di-code while it works": "di-code 工作时输入引导", "Describe what you want to build": "描述你想构建的内容", "Commands": "命令", "No matching commands": "没有匹配的命令", "Add attachment": "添加附件", "Current model does not support image input": "当前模型不支持图片输入", "Model and reasoning": "模型与推理", "Reasoning": "推理", "Reasoning level": "推理级别", "Context usage": "上下文用量", "estimated tokens": "预计 token", "token window": "token 窗口", "cache tokens": "缓存 token", "Stop generating": "停止生成", "Send message": "发送消息", "requests": "次请求", "Compact context": "压缩上下文", "Session messages and accepted attachments are retained in the local session history.": "会话消息和已接受的附件会保留在本地会话历史中。", "Tool approvals": "工具审批", "this tool": "此工具", "Selected": "已选",
	"Current session": "当前会话", "Close session log": "关闭会话日志", "Messages": "消息", "Entries": "条目", "Requests": "请求", "Cumulative input tokens": "累计输入 token", "Cumulative output tokens": "累计输出 token", "Context files": "上下文文件", "tools": "个工具", "resources": "个资源", "Settings source": "设置来源", "no declared capabilities": "未声明能力", "default": "默认", "Active provider": "当前 Provider", "API key is managed by the environment:": "API 密钥由环境变量管理：", "Custom Provider API": "自定义 Provider API", "Custom Provider model": "自定义 Provider 模型", "Custom Provider Base URL": "自定义 Provider 基础 URL", "Custom Provider API key": "自定义 Provider API 密钥", "Session history": "会话历史", "Choose where to continue": "选择继续位置", "Close session tree": "关闭会话树", "Close": "关闭", "Session tree": "会话树", "This session has no history nodes.": "此会话没有历史节点。", "No available nodes": "没有可用节点", "Switching...": "切换中...", "Continue from selected": "从选中位置继续",
	"Skills are untrusted instructions. Project-local Skills appear only when this Workspace is trusted.": "技能是不可信的指令。只有信任此工作区后，项目本地技能才会显示。", "No Skills discovered.": "未发现技能。", "MCP servers": "MCP 服务器", "Connections are external processes or services. Calls are cancellable and server output remains untrusted.": "连接是外部进程或服务。调用可以取消，服务器输出仍是不可信的。", "No configured servers.": "没有已配置的服务器。", "Reconnect": "重新连接", "Remove": "移除", "Add stdio": "添加 stdio", "Project": "项目", "Local": "本地", "User": "用户", "Plugins run in-process. Permissions describe impact and audit scope; they are not an operating-system sandbox.": "插件在同一进程中运行。权限用于描述影响和审计范围，并不是操作系统沙箱。", "No managed plugins installed.": "没有已安装的受管插件。", "Enabled": "已启用", "Agent presets": "Agent 预设", "Presets store non-secret defaults in this browser. Applying one uses explicit settings RPCs; API keys never enter the preset.": "预设仅在此浏览器中保存非敏感默认值。应用预设会调用明确的设置 RPC，API 密钥不会进入预设。", "Apply": "应用", "Delete": "删除", "Preset name": "预设名称", "Save current": "保存当前设置", "Workspace trust": "工作区信任", "Trust controls project-local Skills, MCP configuration, and project composition loading. It does not grant plugin permissions or create a process sandbox.": "信任设置控制项目本地技能、MCP 配置和项目组合加载，不会授予插件权限，也不会创建进程沙箱。", "Trusted Workspace": "已信任工作区", "Untrusted Workspace": "未信任工作区", "Project Skills, MCP, and composition entries may load after validation.": "验证后可以加载项目技能、MCP 和组合条目。", "Only user-scoped resources load; project-local resources remain skipped.": "仅加载用户范围资源，项目本地资源会被跳过。", "Workspace path and secrets stay server-side.": "工作区路径和机密信息保留在服务器端。", "Revoke trust": "撤销信任", "Trust this Workspace": "信任此工作区", "Keyboard actions are presentation-only and never bypass RPC authorization or approvals.": "键盘操作仅用于界面交互，不会绕过 RPC 授权或审批。", "Send": "发送", "New line": "换行", "Cancel active response": "取消当前回复", "Unable to load Skills.": "无法加载技能。", "Unable to load MCP servers.": "无法加载 MCP 服务器。", "MCP configuration failed.": "MCP 配置失败。", "MCP reconnect failed.": "MCP 重连失败。", "MCP remove failed.": "MCP 移除失败。", "Unable to load plugins.": "无法加载插件。", "Plugin update failed.": "插件更新失败。", "Unable to read Workspace trust.": "无法读取工作区信任状态。", "Workspace trust update failed.": "工作区信任状态更新失败。", "Preset apply failed.": "应用预设失败。",
};

interface I18nValue { readonly locale: WebLocale; readonly setLocale: (locale: WebLocale) => void; readonly t: (text: string) => string; }
const I18nContext = createContext<I18nValue>({ locale: "en", setLocale: () => undefined, t: (text) => text });

export function I18nProvider({ initialLocale = "en", children }: { readonly initialLocale?: WebLocale; readonly children: React.ReactNode }): React.JSX.Element {
	const [locale, setLocale] = useState<WebLocale>(initialLocale);
	useEffect(() => { setLocale(initialLocale); }, [initialLocale]);
	useEffect(() => { if (typeof document !== "undefined") document.documentElement.lang = locale; }, [locale]);
	const value = useMemo<I18nValue>(() => ({ locale, setLocale, t: (text) => locale === "zh-CN" ? (zh[text] ?? text) : text }), [locale]);
	return <I18nContext.Provider value={value}>{children}</I18nContext.Provider>;
}

export function useI18n(): I18nValue { return useContext(I18nContext); }
