import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";
import type { Model } from "../src/index.ts";

const packageRoot = fileURLToPath(new URL("..", import.meta.url));
const dataPath = join(packageRoot, "model-data", "anthropic.json");
const generatedPath = join(packageRoot, "src", "providers", "models.generated.ts");

describe("Anthropic model catalog", () => {
	it("has explicit capability metadata", () => {
		expect(existsSync(dataPath)).toBe(true);
		const values = JSON.parse(readFileSync(dataPath, "utf8")) as Record<string, unknown>;
		const model = values["claude-sonnet-4-5"] as Record<string, unknown>;
		expect(model.id).toBe("claude-sonnet-4-5");
		expect(model.compat).toEqual({ tools: "supported", images: "supported", thinking: "supported" });
	});

	it("exports a typed generated runtime catalog", async () => {
		expect(existsSync(generatedPath)).toBe(true);
		const catalog = await import("../src/providers/models.generated.ts");
		const models = catalog.ANTHROPIC_MODELS as readonly Model[];
		expect(models).toHaveLength(1);
		expect(models[0]).toMatchObject({ provider: "anthropic", api: "anthropic-messages" });
	});

	it("does not store credentials in model data", () => {
		expect(readFileSync(dataPath, "utf8")).not.toMatch(
			/"(?:api[_-]?key|authorization|bearer|accessToken|refreshToken)"\s*:/i,
		);
	});

	it("uses a stable generated header and model id", () => {
		const generated = readFileSync(generatedPath, "utf8");
		expect(generated).toContain("auto-generated by scripts/generate-model-data.ts");
		expect(generated).toContain('"claude-sonnet-4-5"');
	});
});
