export type {
	ExtensionApi,
	ExtensionApiContext,
	ExtensionApiInstance,
	ExtensionCommand,
	ExtensionProvider,
	ExtensionSubagent,
	ExtensionTool,
	ExtensionTrustRecord,
	ExtensionTuiOverlay,
	ExtensionWeb,
	PluginModule,
} from "@di-code/plugin-loader";
export {
	computePackageIntegrity,
	computeWebBundleIntegrity,
	createExtensionAPI,
	getPluginDefinition,
	importSetupModule,
	isPluginDefinition,
	isSetupModule,
	normalizePluginSource,
	PluginTrustStore,
	validateNpmTarballIntegrity,
	validatePackageIntegrity,
} from "@di-code/plugin-loader";
export type {
	ConfigSchema,
	Context,
	Disposer,
	Fiber,
	PluginApply,
	PluginCapabilities,
	PluginDefinition,
	PluginStatus,
	Registry,
	RegistryEntry,
	RegistryOwner,
	RegistrySnapshot,
	RuntimeEvent,
	RuntimeMode,
	ServiceKey,
	WebContribution,
	WebManifest,
	WebSlotContribution,
	WebSlotId,
} from "@di-code/plugin-runtime";
export {
	assertWebContribution,
	createServiceKey,
	isPluginStatus,
	isRuntimeEvent,
	isRuntimeMode,
	validateWebContribution,
	validateWebManifest,
	WebSlotRegistry,
	WebSlotRegistryError,
} from "@di-code/plugin-runtime";
export { createFauxProvider } from "./faux-provider.ts";
export type {
	BundleMessage,
	CommandInput,
	CommandOutput,
	CommandRegistration,
	DiagnosticsService,
	Disposer as ExtensionDisposer,
	ExtensionAPI,
	ExtensionApiVersion,
	ExtensionContext,
	ExtensionErrorCode,
	ExtensionErrorShape,
	ExtensionEventMap,
	ExtensionId,
	ExtensionProtocolVersion,
	FileReadInput,
	FileReadOutput,
	FileService,
	HostMessage,
	JobHandle,
	JobStartInput,
	JobsService,
	JsonSchema,
	JsonValue,
	NetworkService,
	OperationOptions,
	PackageIntegritySpec,
	PluginManifestV1,
	PluginSetup,
	PluginTrustRecord,
	ProjectionEnvelope,
	ProviderEvent,
	ProviderRegistration,
	ProviderRequest,
	ProvidersService,
	ReconcileDecision,
	RequestId,
	SessionId,
	SessionPluginRecord,
	SessionService,
	SessionSnapshot,
	SessionsService,
	SubagentRegistration,
	SubagentRun,
	SubagentService,
	SubagentStartInput,
	SubprocessService,
	TaskEvent,
	TaskId,
	TaskReconcileInput,
	TaskReconcileResult,
	TaskResult,
	TaskSnapshot,
	TaskState,
	ToolInput,
	ToolOutput,
	ToolRegistration,
	TuiOverlayRegistration,
	UiCustomInput,
	UiCustomResult,
	UiService,
	WebRegistration,
} from "./freedom-stage0-contracts.ts";
export {
	EXTENSION_API_VERSION,
	EXTENSION_DEFAULT_TIMEOUT_MS,
	EXTENSION_MAX_PAYLOAD_BYTES,
	EXTENSION_PROTOCOL_VERSION,
	isTaskStateTransitionAllowed,
} from "./freedom-stage0-contracts.ts";
export type {
	AgentHookApiVersion,
	AgentHookContext,
	AgentHookEvent,
	AgentHookModifier,
	AgentHookObserver,
	AgentHookPhase,
	AgentHookRegistration,
	AgentHookRegistry,
	AgentPreStepDecision,
	AgentRequestAssembly,
	AgentStepHook,
	AgentStepPhase,
	PluginErrorCode,
	PluginOperationContext,
	PluginSdkApiVersion,
	PromptSection,
	PromptSectionContext,
	PromptSectionRegistration,
	PromptSectionRegistry,
	PromptSectionSnapshot,
	RpcExtensionDescriptor,
	SessionPluginCapabilities,
	SessionPluginContext,
	SessionPluginFactory,
	SessionPluginFactoryOptions,
	SessionPluginHost,
	SessionPluginInitializer,
	SessionPluginRegistration,
	SessionPluginRegistry,
	SessionPluginScope,
	SessionToolPolicy,
	SessionToolPolicyContext,
	ToolPolicyErrorCode,
	ToolPolicyMode,
	ToolPolicySnapshot,
} from "./stage0-contracts.ts";
export {
	AGENT_HOOK_API_VERSION,
	createAgentHookRegistry,
	createPromptSectionRegistry,
	createSessionPluginFactory,
	createSessionPluginRegistry,
	PLUGIN_SDK_API_VERSION,
	PluginLifecycleError,
	sessionPluginRegistryKey,
} from "./stage0-contracts.ts";
export {
	createExtensionContext,
	createExtensionHostServices,
	type ExtensionHostLifecycle,
	type ExtensionHostServices,
	ExtensionRuntimeError,
	type ExtensionRuntimeOptions,
	InMemorySubagentService,
	type TaskRecord,
	type TaskStore,
} from "./stage2-runtime.ts";
export {
	type BridgePort,
	type DurableTaskRecord,
	DurableTaskStore,
	type LiveSessionRuntime,
	replayTaskRecords,
	SessionRuntimeManager,
	type TaskProjection,
	WEB_BUNDLE_CSP,
	WEB_BUNDLE_SANDBOX_FLAGS,
	WebActionRegistry,
	type WebActionValidator,
	WebBundleBridge,
	type WebBundleBridgeOptions,
} from "./stage3-runtime.ts";
export type {
	SessionEventDefinition,
	SessionEventEnvelope,
	SessionEventMigrator,
	SessionEventRegistry,
	SessionEventValidator,
	SessionProjectionDefinition,
	SessionProjectionRegistry,
	SessionProjectionSnapshot,
} from "./stage4-contracts.ts";
export {
	createSessionEventRegistry,
	createSessionProjectionRegistry,
	SESSION_EVENT_API_VERSION,
	SESSION_EVENT_MAX_PAYLOAD_BYTES,
} from "./stage4-contracts.ts";
export type {
	UserInteraction,
	UserInteractionInput,
	UserInteractionIntent,
	UserInteractionKind,
	UserInteractionOption,
	UserInteractionProvider,
	UserInteractionQuestion,
	UserInteractionResult,
	UserInteractionStatus,
} from "./stage6-contracts.ts";
export {
	createFakeInteractionProvider,
	createUserInteraction,
	USER_INTERACTION_API_VERSION,
	UserInteractionError,
} from "./stage6-contracts.ts";
export type {
	ExtensionStateBadge,
	ExtensionSurface,
	ExtensionUiContribution,
	SessionExtensionFacade,
	SessionExtensionRegistry,
} from "./stage7-contracts.ts";
export { createSessionExtensionRegistry, EXTENSION_FACADE_API_VERSION } from "./stage7-contracts.ts";
