import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { fileURLToPath } from "node:url";

type Capability = "supported" | "unsupported" | "unknown";
type CatalogModel = {
	readonly id: string;
	readonly name: string;
	readonly provider: string;
	readonly api: string;
	readonly input: readonly ("text" | "image")[];
	readonly reasoning: boolean;
	readonly contextWindow: number;
	readonly maxOutputTokens: number;
	readonly cost: Readonly<Record<"input" | "output" | "cacheRead" | "cacheWrite", number>>;
	readonly compat: Readonly<Record<"tools" | "images" | "thinking", Capability>>;
};

const packageRoot = fileURLToPath(new URL("..", import.meta.url));
const sourcePaths = {
	anthropic: join(packageRoot, "model-data", "anthropic.json"),
	openai: join(packageRoot, "model-data", "openai.json"),
} as const;
const outputPath = join(packageRoot, "src", "providers", "models.generated.ts");

function isRecord(value: unknown): value is Record<string, unknown> {
	return typeof value === "object" && value !== null && !Array.isArray(value);
}

function assertModel(provider: keyof typeof sourcePaths, key: string, value: unknown): asserts value is CatalogModel {
	if (!isRecord(value)) throw new Error(`model ${key} must be an object`);
	if (value.id !== key) throw new Error(`model ${key} id must match its catalog key`);
	const api = provider === "openai" ? "openai-responses" : "anthropic-messages";
	if (value.provider !== provider) throw new Error(`model ${key} must use provider ${provider}`);
	if (value.api !== api) throw new Error(`model ${key} must use api ${api}`);
	if (typeof value.name !== "string" || value.name.length === 0) throw new Error(`model ${key} name is required`);
	if (!Array.isArray(value.input) || value.input.some((item) => item !== "text" && item !== "image")) throw new Error(`model ${key} input must contain only text or image`);
	if (typeof value.reasoning !== "boolean") throw new Error(`model ${key} reasoning must be boolean`);
	for (const field of ["contextWindow", "maxOutputTokens"] as const) {
		if (!Number.isInteger(value[field]) || (value[field] as number) <= 0) throw new Error(`model ${key} ${field} must be positive`);
	}
	if (!isRecord(value.cost)) throw new Error(`model ${key} cost is required`);
	for (const field of ["input", "output", "cacheRead", "cacheWrite"] as const) {
		const cost = value.cost[field];
		if (typeof cost !== "number" || !Number.isFinite(cost) || cost < 0) throw new Error(`model ${key} cost.${field} must be a non-negative number`);
	}
	if (!isRecord(value.compat)) throw new Error(`model ${key} compat is required`);
	for (const field of ["tools", "images", "thinking"] as const) {
		if (value.compat[field] !== "supported" && value.compat[field] !== "unsupported" && value.compat[field] !== "unknown") throw new Error(`model ${key} compat.${field} is invalid`);
	}
}

function loadModels(provider: keyof typeof sourcePaths): CatalogModel[] {
	const raw: unknown = JSON.parse(readFileSync(sourcePaths[provider], "utf8"));
	if (!isRecord(raw)) throw new Error(`${provider}.json must contain an object`);
	const models = Object.entries(raw).map(([key, value]) => {
		assertModel(provider, key, value);
		return value;
	});
	if (models.length === 0) throw new Error(`${provider}.json must contain at least one model`);
	return models.sort((left, right) => left.id.localeCompare(right.id, "en"));
}

function render(catalogs: Readonly<Record<keyof typeof sourcePaths, readonly CatalogModel[]>>): string {
	const serialized = (provider: keyof typeof sourcePaths): string => JSON.stringify(catalogs[provider], null, 2);
	return `// This file is auto-generated by scripts/generate-model-data.ts\n// Do not edit manually - run 'npm run generate:model-data' to update\n\nimport type { Model } from "../types.ts";\n\nexport interface ModelCompatibility {\n\treadonly tools: "supported" | "unsupported" | "unknown";\n\treadonly images: "supported" | "unsupported" | "unknown";\n\treadonly thinking: "supported" | "unsupported" | "unknown";\n}\n\nexport type CatalogModel = Model & { readonly compat: ModelCompatibility };\n\nexport const ANTHROPIC_MODELS = ${serialized("anthropic")} as unknown as readonly CatalogModel[];\n\nexport const OPENAI_MODELS = ${serialized("openai")} as unknown as readonly CatalogModel[];\n`;
}

const output = render({ anthropic: loadModels("anthropic"), openai: loadModels("openai") });
if (process.argv.includes("--check")) {
	if (!existsSync(outputPath) || readFileSync(outputPath, "utf8") !== output) throw new Error("Generated model catalog is out of date; run npm run generate:model-data");
	console.log("Model catalog is up to date");
} else {
	mkdirSync(join(packageRoot, "src", "providers"), { recursive: true });
	writeFileSync(outputPath, output, "utf8");
	console.log(`Generated ${outputPath}`);
}
