// This file is auto-generated by scripts/generate-model-data.ts
// Do not edit manually - run 'npm run generate:model-data' to update

import type { Model } from "../types.ts";

export interface ModelCompatibility {
	readonly tools: "supported" | "unsupported" | "unknown";
	readonly images: "supported" | "unsupported" | "unknown";
	readonly thinking: "supported" | "unsupported" | "unknown";
}

export type CatalogModel = Model & { readonly compat: ModelCompatibility };

export const ANTHROPIC_MODELS = [
  {
    "id": "claude-sonnet-4-5",
    "name": "Claude Sonnet 4.5",
    "provider": "anthropic",
    "api": "anthropic-messages",
    "input": [
      "text",
      "image"
    ],
    "reasoning": true,
    "contextWindow": 200000,
    "maxOutputTokens": 64000,
    "cost": {
      "input": 3,
      "output": 15,
      "cacheRead": 0.3,
      "cacheWrite": 3.75
    },
    "compat": {
      "tools": "supported",
      "images": "supported",
      "thinking": "supported"
    }
  }
] as unknown as readonly CatalogModel[];

export const OPENAI_MODELS = [
  {
    "id": "gpt-4.1-mini",
    "name": "GPT-4.1 mini",
    "provider": "openai",
    "api": "openai-responses",
    "input": [
      "text",
      "image"
    ],
    "reasoning": true,
    "contextWindow": 1048576,
    "maxOutputTokens": 32768,
    "cost": {
      "input": 0.4,
      "output": 1.6,
      "cacheRead": 0.1,
      "cacheWrite": 0.4
    },
    "compat": {
      "tools": "supported",
      "images": "supported",
      "thinking": "supported"
    }
  },
  {
    "id": "gpt-4o",
    "name": "GPT-4o",
    "provider": "openai",
    "api": "openai-responses",
    "input": [
      "text",
      "image"
    ],
    "reasoning": false,
    "contextWindow": 128000,
    "maxOutputTokens": 16384,
    "cost": {
      "input": 2.5,
      "output": 10,
      "cacheRead": 1.25,
      "cacheWrite": 0
    },
    "compat": {
      "tools": "supported",
      "images": "supported",
      "thinking": "unsupported"
    }
  }
] as unknown as readonly CatalogModel[];
